-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmbNm8wxh9vmYjvu1
Dh1FtiXnPSFyD68dBTrWTIhcCVSgCgYIKoZIzj0DAQehRANCAARUmxdzMoLYLY4y
htpGhO00mKczJ60VxbS4AlSKADmilJwce6EmWtXpBWlS/fWAf1NnoG7HQc7ExrDO
af0tLoty
-----END PRIVATE KEY-----